/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ReferencesBlock = {
  _type: "referencesBlock";
  title?: string;
  references?: Array<{
    name?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    url?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type FaqBlock = {
  _type: "faqBlock";
  title?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type ServicesBlock = {
  _type: "servicesBlock";
  title?: string;
  services?: Array<{
    number?: number;
    name?: string;
    description?: string;
    features?: Array<string>;
    ctaLabel?: string;
    ctaHref?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type ProblemSolutionBlock = {
  _type: "problemSolutionBlock";
  title?: string;
  problems?: Array<{
    number?: number;
    headline?: string;
    description?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type CtaBlock = {
  _type: "ctaBlock";
  headline?: string;
  subtext?: string;
  ctaLabel?: string;
  ctaHref?: string;
  variant?: "primary" | "secondary";
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type TestimonialsBlock = {
  _type: "testimonialsBlock";
  title?: string;
  testimonials?: Array<{
    quote?: string;
    author?: string;
    role?: string;
    avatar?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type FeatureStrip = {
  _type: "featureStrip";
  title?: string;
  features?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type HeroSection = {
  _type: "heroSection";
  headline?: string;
  subheadline?: string;
  ctaLabel?: string;
  ctaHref?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  variant?: "svgPath" | "backgroundImage" | "textOnly";
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  tagline?: string;
  defaultCtaHref?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  footer?: {
    socialLinks?: Array<{
      platform?: string;
      url?: string;
      _key: string;
    }>;
  };
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  author?: string;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  seo?: {
    title?: string;
    description?: string;
  };
  sections?: Array<{
    _key: string;
  } & HeroSection | {
    _key: string;
  } & FeatureStrip | {
    _key: string;
  } & TestimonialsBlock | {
    _key: string;
  } & CtaBlock | {
    _key: string;
  } & ProblemSolutionBlock | {
    _key: string;
  } & ServicesBlock | {
    _key: string;
  } & FaqBlock | {
    _key: string;
  } & ReferencesBlock>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ReferencesBlock | FaqBlock | ServicesBlock | ProblemSolutionBlock | CtaBlock | TestimonialsBlock | FeatureStrip | HeroSection | SiteSettings | TranslationMetadata | InternationalizedArrayReference | InternationalizedArrayReferenceValue | Post | SanityImageCrop | SanityImageHotspot | Slug | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: coalesce(    *[_type == "page" && slug.current == $slug && language == $language][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } },    *[_type == "page" && slug.current == $slug && language == "es"][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } }  )
export type PAGE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  language: string | null;
  sections: Array<{
    _key: string;
    _type: "ctaBlock";
    headline?: string;
    subtext?: string;
    ctaLabel?: string;
    ctaHref?: string;
    variant?: "primary" | "secondary";
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "faqBlock";
    title?: string;
    faqs?: Array<{
      question?: string;
      answer?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "featureStrip";
    title?: string;
    features?: Array<{
      icon?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "heroSection";
    headline?: string;
    subheadline?: string;
    ctaLabel?: string;
    ctaHref?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    variant?: "backgroundImage" | "svgPath" | "textOnly";
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "problemSolutionBlock";
    title?: string;
    problems?: Array<{
      number?: number;
      headline?: string;
      description?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "referencesBlock";
    title?: string;
    references?: Array<{
      name?: string;
      description?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      url?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "servicesBlock";
    title?: string;
    services?: Array<{
      number?: number;
      name?: string;
      description?: string;
      features?: Array<string>;
      ctaLabel?: string;
      ctaHref?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "testimonialsBlock";
    title?: string;
    testimonials?: Array<{
      quote?: string;
      author?: string;
      role?: string;
      avatar?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  }> | null;
} | null;
// Variable: ALL_PAGES_QUERY
// Query: *[_type == "page" && defined(slug.current)]{ slug, language }
export type ALL_PAGES_QUERYResult = Array<{
  slug: Slug | null;
  language: string | null;
}>;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    siteName,    tagline,    defaultCtaHref,    navigation[]{ label, href, _key },    footer{ socialLinks[]{ platform, url, _key } }  }
export type SITE_SETTINGS_QUERYResult = {
  siteName: string | null;
  tagline: string | null;
  defaultCtaHref: string | null;
  navigation: Array<{
    label: string | null;
    href: string | null;
    _key: string;
  }> | null;
  footer: {
    socialLinks: Array<{
      platform: string | null;
      url: string | null;
      _key: string;
    }> | null;
  } | null;
} | null;
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post" && language == $language] | order(publishedAt desc){    _id,    title,    slug,    publishedAt,    excerpt,    mainImage,    author  }
export type ALL_POSTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  author: string | null;
}>;
// Variable: POST_BY_SLUG_QUERY
// Query: coalesce(    *[_type == "post" && slug.current == $slug && language == $language][0]{ _id, title, slug, language, publishedAt, mainImage, excerpt, body, author, seo },    *[_type == "post" && slug.current == $slug && language == "es"][0]{ _id, title, slug, language, publishedAt, mainImage, excerpt, body, author, seo }  )
export type POST_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  language: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  author: string | null;
  seo: {
    title?: string;
    description?: string;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "coalesce(\n    *[_type == \"page\" && slug.current == $slug && language == $language][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } },\n    *[_type == \"page\" && slug.current == $slug && language == \"es\"][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } }\n  )": PAGE_BY_SLUG_QUERYResult;
    "*[_type == \"page\" && defined(slug.current)]{ slug, language }": ALL_PAGES_QUERYResult;
    "*[_type == \"siteSettings\"][0]{\n    siteName,\n    tagline,\n    defaultCtaHref,\n    navigation[]{ label, href, _key },\n    footer{ socialLinks[]{ platform, url, _key } }\n  }": SITE_SETTINGS_QUERYResult;
    "*[_type == \"post\" && language == $language] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    mainImage,\n    author\n  }": ALL_POSTS_QUERYResult;
    "coalesce(\n    *[_type == \"post\" && slug.current == $slug && language == $language][0]{ _id, title, slug, language, publishedAt, mainImage, excerpt, body, author, seo },\n    *[_type == \"post\" && slug.current == $slug && language == \"es\"][0]{ _id, title, slug, language, publishedAt, mainImage, excerpt, body, author, seo }\n  )": POST_BY_SLUG_QUERYResult;
  }
}
