/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type LandingCtaFinal = {
  _type: "landingCtaFinal";
  headline?: string;
  copy?: string;
  ctaLabel?: string;
  ctaHref?: string;
  scarcityText?: string;
  enabled?: boolean;
};

export type LandingFaq = {
  _type: "landingFaq";
  headline?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  enabled?: boolean;
};

export type LandingTestimonials = {
  _type: "landingTestimonials";
  headline?: string;
  subtitle?: string;
  testimonials?: Array<{
    name?: string;
    role?: string;
    quote?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  enabled?: boolean;
};

export type LandingOffer = {
  _type: "landingOffer";
  headline?: string;
  comparison?: Array<{
    before?: string;
    after?: string;
    _key: string;
  }>;
  services?: Array<{
    title?: string;
    _key: string;
  }>;
  ctaLabel?: string;
  ctaHref?: string;
  enabled?: boolean;
};

export type LandingPlan = {
  _type: "landingPlan";
  headline?: string;
  steps?: Array<{
    number?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  enabled?: boolean;
};

export type LandingGuide = {
  _type: "landingGuide";
  headline?: string;
  paragraphs?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  testimonials?: Array<{
    author?: string;
    role?: string;
    quote?: string;
    _key: string;
  }>;
  enabled?: boolean;
};

export type LandingProblem = {
  _type: "landingProblem";
  headline?: string;
  intro?: string;
  problems?: Array<{
    number?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  closing?: string;
  enabled?: boolean;
};

export type LandingHero = {
  _type: "landingHero";
  headline?: string;
  subtitle?: string;
  ctaLabel?: string;
  ctaHref?: string;
  ctaSecondaryLabel?: string;
  ctaSecondaryHref?: string;
  enabled?: boolean;
};

export type ReferencesBlock = {
  _type: "referencesBlock";
  title?: string;
  references?: Array<{
    name?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    url?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type FaqBlock = {
  _type: "faqBlock";
  title?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type ServicesBlock = {
  _type: "servicesBlock";
  title?: string;
  services?: Array<{
    number?: number;
    name?: string;
    description?: string;
    features?: Array<string>;
    ctaLabel?: string;
    ctaHref?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type ProblemSolutionBlock = {
  _type: "problemSolutionBlock";
  title?: string;
  problems?: Array<{
    number?: number;
    headline?: string;
    description?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type CtaBlock = {
  _type: "ctaBlock";
  headline?: string;
  subtext?: string;
  ctaLabel?: string;
  ctaHref?: string;
  variant?: "primary" | "secondary";
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type TestimonialsBlock = {
  _type: "testimonialsBlock";
  title?: string;
  testimonials?: Array<{
    quote?: string;
    author?: string;
    role?: string;
    avatar?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type FeatureStrip = {
  _type: "featureStrip";
  title?: string;
  features?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type HeroSection = {
  _type: "heroSection";
  badge?: string;
  headline?: string;
  highlightedText?: string;
  subheadline?: string;
  ctaLabel?: string;
  ctaHref?: string;
  ctaSecondaryText?: string;
  portraitImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  enabled?: boolean;
  colorScheme?: "light" | "dark";
  spacing?: "compact" | "normal" | "spacious";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  tagline?: string;
  defaultCtaHref?: string;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  navigation?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  footer?: {
    socialLinks?: Array<{
      platform?: string;
      url?: string;
      _key: string;
    }>;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  category?: "tipps" | "fallstudien";
  tags?: Array<string>;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  seo?: {
    title?: string;
    description?: string;
  };
  sections?: Array<{
    _key: string;
  } & HeroSection | {
    _key: string;
  } & FeatureStrip | {
    _key: string;
  } & TestimonialsBlock | {
    _key: string;
  } & CtaBlock | {
    _key: string;
  } & ProblemSolutionBlock | {
    _key: string;
  } & ServicesBlock | {
    _key: string;
  } & FaqBlock | {
    _key: string;
  } & ReferencesBlock | {
    _key: string;
  } & LandingHero | {
    _key: string;
  } & LandingProblem | {
    _key: string;
  } & LandingGuide | {
    _key: string;
  } & LandingPlan | {
    _key: string;
  } & LandingOffer | {
    _key: string;
  } & LandingTestimonials | {
    _key: string;
  } & LandingFaq | {
    _key: string;
  } & LandingCtaFinal>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = LandingCtaFinal | LandingFaq | LandingTestimonials | LandingOffer | LandingPlan | LandingGuide | LandingProblem | LandingHero | ReferencesBlock | FaqBlock | ServicesBlock | ProblemSolutionBlock | CtaBlock | TestimonialsBlock | FeatureStrip | HeroSection | SiteSettings | SanityImageCrop | SanityImageHotspot | TranslationMetadata | InternationalizedArrayReference | InternationalizedArrayReferenceValue | Post | Author | Slug | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: coalesce(    *[_type == "page" && slug.current == $slug && language == $language][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } },    *[_type == "page" && slug.current == $slug && language == "es"][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } }  )
export type PAGE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  language: string | null;
  sections: Array<{
    _key: string;
    _type: "ctaBlock";
    headline?: string;
    subtext?: string;
    ctaLabel?: string;
    ctaHref?: string;
    variant?: "primary" | "secondary";
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "faqBlock";
    title?: string;
    faqs?: Array<{
      question?: string;
      answer?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "featureStrip";
    title?: string;
    features?: Array<{
      icon?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "heroSection";
    badge?: string;
    headline?: string;
    highlightedText?: string;
    subheadline?: string;
    ctaLabel?: string;
    ctaHref?: string;
    ctaSecondaryText?: string;
    portraitImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "landingCtaFinal";
    headline?: string;
    copy?: string;
    ctaLabel?: string;
    ctaHref?: string;
    scarcityText?: string;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingFaq";
    headline?: string;
    faqs?: Array<{
      question?: string;
      answer?: string;
      _key: string;
    }>;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingGuide";
    headline?: string;
    paragraphs?: Array<string>;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    testimonials?: Array<{
      author?: string;
      role?: string;
      quote?: string;
      _key: string;
    }>;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingHero";
    headline?: string;
    subtitle?: string;
    ctaLabel?: string;
    ctaHref?: string;
    ctaSecondaryLabel?: string;
    ctaSecondaryHref?: string;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingOffer";
    headline?: string;
    comparison?: Array<{
      before?: string;
      after?: string;
      _key: string;
    }>;
    services?: Array<{
      title?: string;
      _key: string;
    }>;
    ctaLabel?: string;
    ctaHref?: string;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingPlan";
    headline?: string;
    steps?: Array<{
      number?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingProblem";
    headline?: string;
    intro?: string;
    problems?: Array<{
      number?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
    closing?: string;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "landingTestimonials";
    headline?: string;
    subtitle?: string;
    testimonials?: Array<{
      name?: string;
      role?: string;
      quote?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      _key: string;
    }>;
    enabled?: boolean;
  } | {
    _key: string;
    _type: "problemSolutionBlock";
    title?: string;
    problems?: Array<{
      number?: number;
      headline?: string;
      description?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "referencesBlock";
    title?: string;
    references?: Array<{
      name?: string;
      description?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      url?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "servicesBlock";
    title?: string;
    services?: Array<{
      number?: number;
      name?: string;
      description?: string;
      features?: Array<string>;
      ctaLabel?: string;
      ctaHref?: string;
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  } | {
    _key: string;
    _type: "testimonialsBlock";
    title?: string;
    testimonials?: Array<{
      quote?: string;
      author?: string;
      role?: string;
      avatar?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      _key: string;
    }>;
    enabled?: boolean;
    colorScheme?: "dark" | "light";
    spacing?: "compact" | "normal" | "spacious";
  }> | null;
} | null;
// Variable: ALL_PAGES_QUERY
// Query: *[_type == "page" && defined(slug.current)]{ slug, language }
export type ALL_PAGES_QUERYResult = Array<{
  slug: Slug | null;
  language: string | null;
}>;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    siteName,    tagline,    defaultCtaHref,    navigation[]{ label, href, _key },    footer{ socialLinks[]{ platform, url, _key } }  }
export type SITE_SETTINGS_QUERYResult = {
  siteName: string | null;
  tagline: string | null;
  defaultCtaHref: string | null;
  navigation: Array<{
    label: string | null;
    href: string | null;
    _key: string;
  }> | null;
  footer: {
    socialLinks: Array<{
      platform: string | null;
      url: string | null;
      _key: string;
    }> | null;
  } | null;
} | null;
// Variable: SITE_SETTINGS_SEO_QUERY
// Query: *[_type == "siteSettings"][0]{    siteName,    tagline,    defaultCtaHref,    seo{ title, description, ogImage }  }
export type SITE_SETTINGS_SEO_QUERYResult = {
  siteName: string | null;
  tagline: string | null;
  defaultCtaHref: string | null;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post" && language == $language && defined(publishedAt)] | order(publishedAt desc){    _id,    title,    slug,    publishedAt,    excerpt,    mainImage,    category,    tags,    "estimatedReadingTime": round(length(pt::text(body)) / 5 / 180),    "author": author->{ name, image }  }
export type ALL_POSTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  category: "fallstudien" | "tipps" | null;
  tags: Array<string> | null;
  estimatedReadingTime: number;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;
// Variable: ALL_POSTS_FOR_SITEMAP_QUERY
// Query: *[_type == "post" && defined(publishedAt) && defined(slug.current)]{    slug,    _updatedAt,    language  }
export type ALL_POSTS_FOR_SITEMAP_QUERYResult = Array<{
  slug: Slug | null;
  _updatedAt: string;
  language: string | null;
}>;
// Variable: POST_BY_SLUG_QUERY
// Query: coalesce(    *[_type == "post" && slug.current == $slug && language == $language][0]{      _id, title, slug, language, publishedAt, _updatedAt, mainImage, excerpt, body,      category, tags,      "estimatedReadingTime": round(length(pt::text(body)) / 5 / 180),      "author": author->{ name, bio, image },      seo    },    *[_type == "post" && slug.current == $slug && language == "es"][0]{      _id, title, slug, language, publishedAt, _updatedAt, mainImage, excerpt, body,      category, tags,      "estimatedReadingTime": round(length(pt::text(body)) / 5 / 180),      "author": author->{ name, bio, image },      seo    }  )
export type POST_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  language: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
  category: "fallstudien" | "tipps" | null;
  tags: Array<string> | null;
  estimatedReadingTime: number;
  author: {
    name: string | null;
    bio: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  seo: {
    title?: string;
    description?: string;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "coalesce(\n    *[_type == \"page\" && slug.current == $slug && language == $language][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } },\n    *[_type == \"page\" && slug.current == $slug && language == \"es\"][0]{ _id, title, slug, language, sections[]{ ..., _type, _key } }\n  )": PAGE_BY_SLUG_QUERYResult;
    "*[_type == \"page\" && defined(slug.current)]{ slug, language }": ALL_PAGES_QUERYResult;
    "*[_type == \"siteSettings\"][0]{\n    siteName,\n    tagline,\n    defaultCtaHref,\n    navigation[]{ label, href, _key },\n    footer{ socialLinks[]{ platform, url, _key } }\n  }": SITE_SETTINGS_QUERYResult;
    "*[_type == \"siteSettings\"][0]{\n    siteName,\n    tagline,\n    defaultCtaHref,\n    seo{ title, description, ogImage }\n  }": SITE_SETTINGS_SEO_QUERYResult;
    "*[_type == \"post\" && language == $language && defined(publishedAt)] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    mainImage,\n    category,\n    tags,\n    \"estimatedReadingTime\": round(length(pt::text(body)) / 5 / 180),\n    \"author\": author->{ name, image }\n  }": ALL_POSTS_QUERYResult;
    "*[_type == \"post\" && defined(publishedAt) && defined(slug.current)]{\n    slug,\n    _updatedAt,\n    language\n  }": ALL_POSTS_FOR_SITEMAP_QUERYResult;
    "coalesce(\n    *[_type == \"post\" && slug.current == $slug && language == $language][0]{\n      _id, title, slug, language, publishedAt, _updatedAt, mainImage, excerpt, body,\n      category, tags,\n      \"estimatedReadingTime\": round(length(pt::text(body)) / 5 / 180),\n      \"author\": author->{ name, bio, image },\n      seo\n    },\n    *[_type == \"post\" && slug.current == $slug && language == \"es\"][0]{\n      _id, title, slug, language, publishedAt, _updatedAt, mainImage, excerpt, body,\n      category, tags,\n      \"estimatedReadingTime\": round(length(pt::text(body)) / 5 / 180),\n      \"author\": author->{ name, bio, image },\n      seo\n    }\n  )": POST_BY_SLUG_QUERYResult;
  }
}
